a = dict(x=1,y=4)
b = dict(y=2)
c = dict(z=3)
d = {"x":1,"y":"2"}
e = dict({"Sabrina":"72086616"})
f = dict(zip(a,b))
g = dict(zip(b,c))
h = dict({"Hola":"Bienvenido"})
i = dict({"Cachorrito":"Cachorrita"})
j = dict(m=4)


print(a["x"])
print(a["y"])
print(b['y'])
print(c["z"])
print(d["x"])
print(d["y"])
print(e["Sabrina"])
print(f["x"])
print(g["y"])
print(h["Hola"])
