a = dict(x=1,y=4)
b = dict(y=2)
c = dict(z=3)
d = {"x":1,"y":"2"}
e = dict({"Sabrina":"72086616"})
f = dict(zip(a,b))
g = dict(zip(b,c))
h = dict({"Hola":"Bienvenido"})
i = dict({"Cachorrito":"Cachorrita"})
j = dict(m=4)

print(a.values())
print(b.values())
print(c.values())
print(d.values())
print(e.values())
print(f.values())
print(g.values())
print(h.values())
print(i.values())
print(j.values())
